/*
 * generated by Xtext 2.17.0
 */
package co.edu.escuelaing.reactivexd.ui;

import co.edu.escuelaing.reactivexd.ui.internal.ReactivexdActivator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ReactiveXDExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(ReactivexdActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		ReactivexdActivator activator = ReactivexdActivator.getInstance();
		return activator != null ? activator.getInjector(ReactivexdActivator.CO_EDU_ESCUELAING_REACTIVEXD_REACTIVEXD) : null;
	}

}
