/**
 * generated by Xtext 2.17.0
 */
package co.edu.escuelaing.reactivexd;

import co.edu.escuelaing.reactivexd.ReactiveXDStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ReactiveXDStandaloneSetup extends ReactiveXDStandaloneSetupGenerated {
  public static void doSetup() {
    new ReactiveXDStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
