/**
 * generated by Xtext 2.17.0
 */
package co.edu.escuelaing.reactivexd;

import co.edu.escuelaing.reactivexd.AbstractReactiveXDRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ReactiveXDRuntimeModule extends AbstractReactiveXDRuntimeModule {
}
