/*
 * generated by Xtext 2.17.0
 */
package co.edu.escuelaing.reactivexd.ui.tests;

import co.edu.escuelaing.reactivexd.ui.internal.ReactivexdActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ReactiveXDUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ReactivexdActivator.getInstance().getInjector("co.edu.escuelaing.reactivexd.ReactiveXD");
	}

}
