/**
 * generated by Xtext 2.17.0
 */
package co.edu.escuelaing.reactivexd.ui.contentassist;

import co.edu.escuelaing.reactivexd.ui.contentassist.AbstractReactiveXDProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ReactiveXDProposalProvider extends AbstractReactiveXDProposalProvider {
}
