/*
 * generated by Xtext 2.17.0
 */
package co.edu.escuelaing.reactivexd.ui.editor;

import org.eclipse.xtext.xbase.ui.editor.XbaseEditor;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass.
 */
public class ReactiveXDEditor extends XbaseEditor {
}
