/**
 * generated by Xtext 2.17.0
 */
package co.edu.escuelaing.reactivexd.scoping;

import co.edu.escuelaing.reactivexd.scoping.AbstractReactiveXDScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ReactiveXDScopeProvider extends AbstractReactiveXDScopeProvider {
}
