/**
 * generated by Xtext 2.17.0
 */
package co.edu.escuelaing.reactivexd.ui;

import co.edu.escuelaing.reactivexd.ui.AbstractReactiveXDUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ReactiveXDUiModule extends AbstractReactiveXDUiModule {
  public ReactiveXDUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
