/**
 * generated by Xtext 2.17.0
 */
package co.edu.escuelaing.reactivexd.validation;

import co.edu.escuelaing.reactivexd.validation.AbstractReactiveXDValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ReactiveXDValidator extends AbstractReactiveXDValidator {
}
