/**
 * generated by Xtext 2.17.0
 */
package co.edu.escuelaing.reactivexd.ide;

import co.edu.escuelaing.reactivexd.ide.AbstractReactiveXDIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ReactiveXDIdeModule extends AbstractReactiveXDIdeModule {
}
