/**
 * generated by Xtext 2.17.0
 */
package co.edu.escuelaing.reactivexd.ide;

import co.edu.escuelaing.reactivexd.ReactiveXDRuntimeModule;
import co.edu.escuelaing.reactivexd.ReactiveXDStandaloneSetup;
import co.edu.escuelaing.reactivexd.ide.ReactiveXDIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ReactiveXDIdeSetup extends ReactiveXDStandaloneSetup {
  @Override
  public Injector createInjector() {
    ReactiveXDRuntimeModule _reactiveXDRuntimeModule = new ReactiveXDRuntimeModule();
    ReactiveXDIdeModule _reactiveXDIdeModule = new ReactiveXDIdeModule();
    return Guice.createInjector(Modules2.mixin(_reactiveXDRuntimeModule, _reactiveXDIdeModule));
  }
}
