/*
 * generated by Xtext 2.17.0
 */
package co.edu.escuelaing.reactivexd.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractReactiveXDScopeProvider extends XbaseBatchScopeProvider {
}
