/**
 * generated by Xtext 2.17.0
 */
package co.edu.escuelaing.reactivexd.reactiveXD;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>And Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.edu.escuelaing.reactivexd.reactiveXD.AndEvent#getLeft <em>Left</em>}</li>
 *   <li>{@link co.edu.escuelaing.reactivexd.reactiveXD.AndEvent#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see co.edu.escuelaing.reactivexd.reactiveXD.ReactiveXDPackage#getAndEvent()
 * @model
 * @generated
 */
public interface AndEvent extends EventExpression
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(EventExpression)
   * @see co.edu.escuelaing.reactivexd.reactiveXD.ReactiveXDPackage#getAndEvent_Left()
   * @model containment="true"
   * @generated
   */
  EventExpression getLeft();

  /**
   * Sets the value of the '{@link co.edu.escuelaing.reactivexd.reactiveXD.AndEvent#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(EventExpression value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(EventExpression)
   * @see co.edu.escuelaing.reactivexd.reactiveXD.ReactiveXDPackage#getAndEvent_Right()
   * @model containment="true"
   * @generated
   */
  EventExpression getRight();

  /**
   * Sets the value of the '{@link co.edu.escuelaing.reactivexd.reactiveXD.AndEvent#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(EventExpression value);

} // AndEvent
