/**
 * generated by Xtext 2.17.0
 */
package co.edu.escuelaing.reactivexd.reactiveXD;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.edu.escuelaing.reactivexd.reactiveXD.EventExpression#getEventType <em>Event Type</em>}</li>
 *   <li>{@link co.edu.escuelaing.reactivexd.reactiveXD.EventExpression#getOp <em>Op</em>}</li>
 * </ul>
 *
 * @see co.edu.escuelaing.reactivexd.reactiveXD.ReactiveXDPackage#getEventExpression()
 * @model
 * @generated
 */
public interface EventExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Event Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event Type</em>' containment reference.
   * @see #setEventType(EventPredicate)
   * @see co.edu.escuelaing.reactivexd.reactiveXD.ReactiveXDPackage#getEventExpression_EventType()
   * @model containment="true"
   * @generated
   */
  EventPredicate getEventType();

  /**
   * Sets the value of the '{@link co.edu.escuelaing.reactivexd.reactiveXD.EventExpression#getEventType <em>Event Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event Type</em>' containment reference.
   * @see #getEventType()
   * @generated
   */
  void setEventType(EventPredicate value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see co.edu.escuelaing.reactivexd.reactiveXD.ReactiveXDPackage#getEventExpression_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link co.edu.escuelaing.reactivexd.reactiveXD.EventExpression#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

} // EventExpression
