/**
 * generated by Xtext 2.17.0
 */
package co.edu.escuelaing.reactivexd.reactiveXD;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event Predicate</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see co.edu.escuelaing.reactivexd.reactiveXD.ReactiveXDPackage#getEventPredicate()
 * @model
 * @generated
 */
public interface EventPredicate extends EObject
{
} // EventPredicate
