/**
 * generated by Xtext 2.17.0
 */
package co.edu.escuelaing.reactivexd.reactiveXD;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.xtext.common.types.JvmTypeReference;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>JVMTYPE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.edu.escuelaing.reactivexd.reactiveXD.JVMTYPE#getAstk <em>Astk</em>}</li>
 *   <li>{@link co.edu.escuelaing.reactivexd.reactiveXD.JVMTYPE#getJvmRef <em>Jvm Ref</em>}</li>
 * </ul>
 *
 * @see co.edu.escuelaing.reactivexd.reactiveXD.ReactiveXDPackage#getJVMTYPE()
 * @model
 * @generated
 */
public interface JVMTYPE extends EObject
{
  /**
   * Returns the value of the '<em><b>Astk</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Astk</em>' attribute.
   * @see #setAstk(String)
   * @see co.edu.escuelaing.reactivexd.reactiveXD.ReactiveXDPackage#getJVMTYPE_Astk()
   * @model
   * @generated
   */
  String getAstk();

  /**
   * Sets the value of the '{@link co.edu.escuelaing.reactivexd.reactiveXD.JVMTYPE#getAstk <em>Astk</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Astk</em>' attribute.
   * @see #getAstk()
   * @generated
   */
  void setAstk(String value);

  /**
   * Returns the value of the '<em><b>Jvm Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Jvm Ref</em>' containment reference.
   * @see #setJvmRef(JvmTypeReference)
   * @see co.edu.escuelaing.reactivexd.reactiveXD.ReactiveXDPackage#getJVMTYPE_JvmRef()
   * @model containment="true"
   * @generated
   */
  JvmTypeReference getJvmRef();

  /**
   * Sets the value of the '{@link co.edu.escuelaing.reactivexd.reactiveXD.JVMTYPE#getJvmRef <em>Jvm Ref</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Jvm Ref</em>' containment reference.
   * @see #getJvmRef()
   * @generated
   */
  void setJvmRef(JvmTypeReference value);

} // JVMTYPE
