/**
 * generated by Xtext 2.17.0
 */
package co.edu.escuelaing.reactivexd.reactiveXD;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Kind Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.edu.escuelaing.reactivexd.reactiveXD.KindAttribute#getLocat <em>Locat</em>}</li>
 * </ul>
 *
 * @see co.edu.escuelaing.reactivexd.reactiveXD.ReactiveXDPackage#getKindAttribute()
 * @model
 * @generated
 */
public interface KindAttribute extends EventPredicate
{
  /**
   * Returns the value of the '<em><b>Locat</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Locat</em>' attribute.
   * @see #setLocat(String)
   * @see co.edu.escuelaing.reactivexd.reactiveXD.ReactiveXDPackage#getKindAttribute_Locat()
   * @model
   * @generated
   */
  String getLocat();

  /**
   * Sets the value of the '{@link co.edu.escuelaing.reactivexd.reactiveXD.KindAttribute#getLocat <em>Locat</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Locat</em>' attribute.
   * @see #getLocat()
   * @generated
   */
  void setLocat(String value);

} // KindAttribute
