/**
 * generated by Xtext 2.17.0
 */
package co.edu.escuelaing.reactivexd.reactiveXD;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Obsrv Assig</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.edu.escuelaing.reactivexd.reactiveXD.ObsrvAssig#getProps <em>Props</em>}</li>
 * </ul>
 *
 * @see co.edu.escuelaing.reactivexd.reactiveXD.ReactiveXDPackage#getObsrvAssig()
 * @model
 * @generated
 */
public interface ObsrvAssig extends EObject
{
  /**
   * Returns the value of the '<em><b>Props</b></em>' containment reference list.
   * The list contents are of type {@link co.edu.escuelaing.reactivexd.reactiveXD.EventExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Props</em>' containment reference list.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.ReactiveXDPackage#getObsrvAssig_Props()
   * @model containment="true"
   * @generated
   */
  EList<EventExpression> getProps();

} // ObsrvAssig
