/**
 * generated by Xtext 2.17.0
 */
package co.edu.escuelaing.reactivexd.reactiveXD;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Obsrv Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.edu.escuelaing.reactivexd.reactiveXD.ObsrvDecl#getType <em>Type</em>}</li>
 *   <li>{@link co.edu.escuelaing.reactivexd.reactiveXD.ObsrvDecl#getAssignment <em>Assignment</em>}</li>
 * </ul>
 *
 * @see co.edu.escuelaing.reactivexd.reactiveXD.ReactiveXDPackage#getObsrvDecl()
 * @model
 * @generated
 */
public interface ObsrvDecl extends Decl
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link co.edu.escuelaing.reactivexd.reactiveXD.EventType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.EventType
   * @see #setType(EventType)
   * @see co.edu.escuelaing.reactivexd.reactiveXD.ReactiveXDPackage#getObsrvDecl_Type()
   * @model
   * @generated
   */
  EventType getType();

  /**
   * Sets the value of the '{@link co.edu.escuelaing.reactivexd.reactiveXD.ObsrvDecl#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.EventType
   * @see #getType()
   * @generated
   */
  void setType(EventType value);

  /**
   * Returns the value of the '<em><b>Assignment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assignment</em>' containment reference.
   * @see #setAssignment(ObsrvAssig)
   * @see co.edu.escuelaing.reactivexd.reactiveXD.ReactiveXDPackage#getObsrvDecl_Assignment()
   * @model containment="true"
   * @generated
   */
  ObsrvAssig getAssignment();

  /**
   * Sets the value of the '{@link co.edu.escuelaing.reactivexd.reactiveXD.ObsrvDecl#getAssignment <em>Assignment</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Assignment</em>' containment reference.
   * @see #getAssignment()
   * @generated
   */
  void setAssignment(ObsrvAssig value);

} // ObsrvDecl
