/**
 * generated by Xtext 2.17.0
 */
package co.edu.escuelaing.reactivexd.reactiveXD;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see co.edu.escuelaing.reactivexd.reactiveXD.ReactiveXDFactory
 * @model kind="package"
 * @generated
 */
public interface ReactiveXDPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "reactiveXD";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.escuelaing.edu.co/reactivexd/ReactiveXD";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "reactiveXD";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ReactiveXDPackage eINSTANCE = co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl.init();

  /**
   * The meta object id for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ModelImpl
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Import Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__IMPORT_SECTION = 1;

  /**
   * The feature id for the '<em><b>Type Declaration</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__TYPE_DECLARATION = 2;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.impl.DeclImpl <em>Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.DeclImpl
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getDecl()
   * @generated
   */
  int DECL = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECL__NAME = 0;

  /**
   * The number of structural features of the '<em>Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.impl.ObsrvDeclImpl <em>Obsrv Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ObsrvDeclImpl
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getObsrvDecl()
   * @generated
   */
  int OBSRV_DECL = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBSRV_DECL__NAME = DECL__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBSRV_DECL__TYPE = DECL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Assignment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBSRV_DECL__ASSIGNMENT = DECL_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Obsrv Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBSRV_DECL_FEATURE_COUNT = DECL_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.impl.ObsrvAssigImpl <em>Obsrv Assig</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ObsrvAssigImpl
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getObsrvAssig()
   * @generated
   */
  int OBSRV_ASSIG = 3;

  /**
   * The feature id for the '<em><b>Props</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBSRV_ASSIG__PROPS = 0;

  /**
   * The number of structural features of the '<em>Obsrv Assig</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBSRV_ASSIG_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.impl.EventExpressionImpl <em>Event Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.EventExpressionImpl
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getEventExpression()
   * @generated
   */
  int EVENT_EXPRESSION = 4;

  /**
   * The feature id for the '<em><b>Event Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_EXPRESSION__EVENT_TYPE = 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_EXPRESSION__OP = 1;

  /**
   * The number of structural features of the '<em>Event Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_EXPRESSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.impl.EventPredicateImpl <em>Event Predicate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.EventPredicateImpl
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getEventPredicate()
   * @generated
   */
  int EVENT_PREDICATE = 5;

  /**
   * The number of structural features of the '<em>Event Predicate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_PREDICATE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.impl.TriggerImpl <em>Trigger</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.TriggerImpl
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getTrigger()
   * @generated
   */
  int TRIGGER = 6;

  /**
   * The feature id for the '<em><b>Trigger Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__TRIGGER_TYPE = EVENT_PREDICATE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Returndef</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__RETURNDEF = EVENT_PREDICATE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Esig</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__ESIG = EVENT_PREDICATE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__PARAMS = EVENT_PREDICATE_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Trigger</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER_FEATURE_COUNT = EVENT_PREDICATE_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.impl.JVMTYPEImpl <em>JVMTYPE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.JVMTYPEImpl
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getJVMTYPE()
   * @generated
   */
  int JVMTYPE = 7;

  /**
   * The feature id for the '<em><b>Astk</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JVMTYPE__ASTK = 0;

  /**
   * The feature id for the '<em><b>Jvm Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JVMTYPE__JVM_REF = 1;

  /**
   * The number of structural features of the '<em>JVMTYPE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JVMTYPE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.impl.KindAttributeImpl <em>Kind Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.KindAttributeImpl
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getKindAttribute()
   * @generated
   */
  int KIND_ATTRIBUTE = 8;

  /**
   * The feature id for the '<em><b>Locat</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KIND_ATTRIBUTE__LOCAT = EVENT_PREDICATE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Kind Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KIND_ATTRIBUTE_FEATURE_COUNT = EVENT_PREDICATE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.impl.MSigImpl <em>MSig</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.MSigImpl
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getMSig()
   * @generated
   */
  int MSIG = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MSIG__NAME = DECL__NAME;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MSIG__PARAMS = DECL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MSIG__TYPE = DECL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MSIG__BODY = DECL_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>MSig</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MSIG_FEATURE_COUNT = DECL_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.impl.OrEventImpl <em>Or Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.OrEventImpl
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getOrEvent()
   * @generated
   */
  int OR_EVENT = 10;

  /**
   * The feature id for the '<em><b>Event Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_EVENT__EVENT_TYPE = EVENT_EXPRESSION__EVENT_TYPE;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_EVENT__OP = EVENT_EXPRESSION__OP;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_EVENT__LEFT = EVENT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_EVENT__RIGHT = EVENT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Or Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_EVENT_FEATURE_COUNT = EVENT_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.impl.AndEventImpl <em>And Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.AndEventImpl
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getAndEvent()
   * @generated
   */
  int AND_EVENT = 11;

  /**
   * The feature id for the '<em><b>Event Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EVENT__EVENT_TYPE = EVENT_EXPRESSION__EVENT_TYPE;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EVENT__OP = EVENT_EXPRESSION__OP;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EVENT__LEFT = EVENT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EVENT__RIGHT = EVENT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>And Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EVENT_FEATURE_COUNT = EVENT_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.impl.UnaryEventImpl <em>Unary Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.UnaryEventImpl
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getUnaryEvent()
   * @generated
   */
  int UNARY_EVENT = 12;

  /**
   * The feature id for the '<em><b>Event Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_EVENT__EVENT_TYPE = EVENT_EXPRESSION__EVENT_TYPE;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_EVENT__OP = EVENT_EXPRESSION__OP;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_EVENT__EXPR = EVENT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Unary Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_EVENT_FEATURE_COUNT = EVENT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.EventType <em>Event Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.escuelaing.reactivexd.reactiveXD.EventType
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getEventType()
   * @generated
   */
  int EVENT_TYPE = 13;

  /**
   * The meta object id for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.TPrefix <em>TPrefix</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.escuelaing.reactivexd.reactiveXD.TPrefix
   * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getTPrefix()
   * @generated
   */
  int TPREFIX = 14;


  /**
   * Returns the meta object for class '{@link co.edu.escuelaing.reactivexd.reactiveXD.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link co.edu.escuelaing.reactivexd.reactiveXD.Model#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.Model#getName()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Name();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.escuelaing.reactivexd.reactiveXD.Model#getImportSection <em>Import Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Import Section</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.Model#getImportSection()
   * @see #getModel()
   * @generated
   */
  EReference getModel_ImportSection();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.escuelaing.reactivexd.reactiveXD.Model#getTypeDeclaration <em>Type Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Type Declaration</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.Model#getTypeDeclaration()
   * @see #getModel()
   * @generated
   */
  EReference getModel_TypeDeclaration();

  /**
   * Returns the meta object for class '{@link co.edu.escuelaing.reactivexd.reactiveXD.Decl <em>Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Decl</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.Decl
   * @generated
   */
  EClass getDecl();

  /**
   * Returns the meta object for the attribute '{@link co.edu.escuelaing.reactivexd.reactiveXD.Decl#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.Decl#getName()
   * @see #getDecl()
   * @generated
   */
  EAttribute getDecl_Name();

  /**
   * Returns the meta object for class '{@link co.edu.escuelaing.reactivexd.reactiveXD.ObsrvDecl <em>Obsrv Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Obsrv Decl</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.ObsrvDecl
   * @generated
   */
  EClass getObsrvDecl();

  /**
   * Returns the meta object for the attribute '{@link co.edu.escuelaing.reactivexd.reactiveXD.ObsrvDecl#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.ObsrvDecl#getType()
   * @see #getObsrvDecl()
   * @generated
   */
  EAttribute getObsrvDecl_Type();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.escuelaing.reactivexd.reactiveXD.ObsrvDecl#getAssignment <em>Assignment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Assignment</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.ObsrvDecl#getAssignment()
   * @see #getObsrvDecl()
   * @generated
   */
  EReference getObsrvDecl_Assignment();

  /**
   * Returns the meta object for class '{@link co.edu.escuelaing.reactivexd.reactiveXD.ObsrvAssig <em>Obsrv Assig</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Obsrv Assig</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.ObsrvAssig
   * @generated
   */
  EClass getObsrvAssig();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.escuelaing.reactivexd.reactiveXD.ObsrvAssig#getProps <em>Props</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Props</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.ObsrvAssig#getProps()
   * @see #getObsrvAssig()
   * @generated
   */
  EReference getObsrvAssig_Props();

  /**
   * Returns the meta object for class '{@link co.edu.escuelaing.reactivexd.reactiveXD.EventExpression <em>Event Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event Expression</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.EventExpression
   * @generated
   */
  EClass getEventExpression();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.escuelaing.reactivexd.reactiveXD.EventExpression#getEventType <em>Event Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Event Type</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.EventExpression#getEventType()
   * @see #getEventExpression()
   * @generated
   */
  EReference getEventExpression_EventType();

  /**
   * Returns the meta object for the attribute '{@link co.edu.escuelaing.reactivexd.reactiveXD.EventExpression#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.EventExpression#getOp()
   * @see #getEventExpression()
   * @generated
   */
  EAttribute getEventExpression_Op();

  /**
   * Returns the meta object for class '{@link co.edu.escuelaing.reactivexd.reactiveXD.EventPredicate <em>Event Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event Predicate</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.EventPredicate
   * @generated
   */
  EClass getEventPredicate();

  /**
   * Returns the meta object for class '{@link co.edu.escuelaing.reactivexd.reactiveXD.Trigger <em>Trigger</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trigger</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.Trigger
   * @generated
   */
  EClass getTrigger();

  /**
   * Returns the meta object for the attribute '{@link co.edu.escuelaing.reactivexd.reactiveXD.Trigger#getTriggerType <em>Trigger Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Trigger Type</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.Trigger#getTriggerType()
   * @see #getTrigger()
   * @generated
   */
  EAttribute getTrigger_TriggerType();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.escuelaing.reactivexd.reactiveXD.Trigger#getReturndef <em>Returndef</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Returndef</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.Trigger#getReturndef()
   * @see #getTrigger()
   * @generated
   */
  EReference getTrigger_Returndef();

  /**
   * Returns the meta object for the attribute '{@link co.edu.escuelaing.reactivexd.reactiveXD.Trigger#getEsig <em>Esig</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Esig</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.Trigger#getEsig()
   * @see #getTrigger()
   * @generated
   */
  EAttribute getTrigger_Esig();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.escuelaing.reactivexd.reactiveXD.Trigger#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.Trigger#getParams()
   * @see #getTrigger()
   * @generated
   */
  EReference getTrigger_Params();

  /**
   * Returns the meta object for class '{@link co.edu.escuelaing.reactivexd.reactiveXD.JVMTYPE <em>JVMTYPE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JVMTYPE</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.JVMTYPE
   * @generated
   */
  EClass getJVMTYPE();

  /**
   * Returns the meta object for the attribute '{@link co.edu.escuelaing.reactivexd.reactiveXD.JVMTYPE#getAstk <em>Astk</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Astk</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.JVMTYPE#getAstk()
   * @see #getJVMTYPE()
   * @generated
   */
  EAttribute getJVMTYPE_Astk();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.escuelaing.reactivexd.reactiveXD.JVMTYPE#getJvmRef <em>Jvm Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Jvm Ref</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.JVMTYPE#getJvmRef()
   * @see #getJVMTYPE()
   * @generated
   */
  EReference getJVMTYPE_JvmRef();

  /**
   * Returns the meta object for class '{@link co.edu.escuelaing.reactivexd.reactiveXD.KindAttribute <em>Kind Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Kind Attribute</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.KindAttribute
   * @generated
   */
  EClass getKindAttribute();

  /**
   * Returns the meta object for the attribute '{@link co.edu.escuelaing.reactivexd.reactiveXD.KindAttribute#getLocat <em>Locat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Locat</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.KindAttribute#getLocat()
   * @see #getKindAttribute()
   * @generated
   */
  EAttribute getKindAttribute_Locat();

  /**
   * Returns the meta object for class '{@link co.edu.escuelaing.reactivexd.reactiveXD.MSig <em>MSig</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MSig</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.MSig
   * @generated
   */
  EClass getMSig();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.escuelaing.reactivexd.reactiveXD.MSig#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.MSig#getParams()
   * @see #getMSig()
   * @generated
   */
  EReference getMSig_Params();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.escuelaing.reactivexd.reactiveXD.MSig#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.MSig#getType()
   * @see #getMSig()
   * @generated
   */
  EReference getMSig_Type();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.escuelaing.reactivexd.reactiveXD.MSig#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.MSig#getBody()
   * @see #getMSig()
   * @generated
   */
  EReference getMSig_Body();

  /**
   * Returns the meta object for class '{@link co.edu.escuelaing.reactivexd.reactiveXD.OrEvent <em>Or Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or Event</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.OrEvent
   * @generated
   */
  EClass getOrEvent();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.escuelaing.reactivexd.reactiveXD.OrEvent#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.OrEvent#getLeft()
   * @see #getOrEvent()
   * @generated
   */
  EReference getOrEvent_Left();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.escuelaing.reactivexd.reactiveXD.OrEvent#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.OrEvent#getRight()
   * @see #getOrEvent()
   * @generated
   */
  EReference getOrEvent_Right();

  /**
   * Returns the meta object for class '{@link co.edu.escuelaing.reactivexd.reactiveXD.AndEvent <em>And Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And Event</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.AndEvent
   * @generated
   */
  EClass getAndEvent();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.escuelaing.reactivexd.reactiveXD.AndEvent#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.AndEvent#getLeft()
   * @see #getAndEvent()
   * @generated
   */
  EReference getAndEvent_Left();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.escuelaing.reactivexd.reactiveXD.AndEvent#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.AndEvent#getRight()
   * @see #getAndEvent()
   * @generated
   */
  EReference getAndEvent_Right();

  /**
   * Returns the meta object for class '{@link co.edu.escuelaing.reactivexd.reactiveXD.UnaryEvent <em>Unary Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Unary Event</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.UnaryEvent
   * @generated
   */
  EClass getUnaryEvent();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.escuelaing.reactivexd.reactiveXD.UnaryEvent#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.UnaryEvent#getExpr()
   * @see #getUnaryEvent()
   * @generated
   */
  EReference getUnaryEvent_Expr();

  /**
   * Returns the meta object for enum '{@link co.edu.escuelaing.reactivexd.reactiveXD.EventType <em>Event Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Event Type</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.EventType
   * @generated
   */
  EEnum getEventType();

  /**
   * Returns the meta object for enum '{@link co.edu.escuelaing.reactivexd.reactiveXD.TPrefix <em>TPrefix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>TPrefix</em>'.
   * @see co.edu.escuelaing.reactivexd.reactiveXD.TPrefix
   * @generated
   */
  EEnum getTPrefix();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ReactiveXDFactory getReactiveXDFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ModelImpl
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__NAME = eINSTANCE.getModel_Name();

    /**
     * The meta object literal for the '<em><b>Import Section</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__IMPORT_SECTION = eINSTANCE.getModel_ImportSection();

    /**
     * The meta object literal for the '<em><b>Type Declaration</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__TYPE_DECLARATION = eINSTANCE.getModel_TypeDeclaration();

    /**
     * The meta object literal for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.impl.DeclImpl <em>Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.DeclImpl
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getDecl()
     * @generated
     */
    EClass DECL = eINSTANCE.getDecl();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECL__NAME = eINSTANCE.getDecl_Name();

    /**
     * The meta object literal for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.impl.ObsrvDeclImpl <em>Obsrv Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ObsrvDeclImpl
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getObsrvDecl()
     * @generated
     */
    EClass OBSRV_DECL = eINSTANCE.getObsrvDecl();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBSRV_DECL__TYPE = eINSTANCE.getObsrvDecl_Type();

    /**
     * The meta object literal for the '<em><b>Assignment</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBSRV_DECL__ASSIGNMENT = eINSTANCE.getObsrvDecl_Assignment();

    /**
     * The meta object literal for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.impl.ObsrvAssigImpl <em>Obsrv Assig</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ObsrvAssigImpl
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getObsrvAssig()
     * @generated
     */
    EClass OBSRV_ASSIG = eINSTANCE.getObsrvAssig();

    /**
     * The meta object literal for the '<em><b>Props</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBSRV_ASSIG__PROPS = eINSTANCE.getObsrvAssig_Props();

    /**
     * The meta object literal for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.impl.EventExpressionImpl <em>Event Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.EventExpressionImpl
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getEventExpression()
     * @generated
     */
    EClass EVENT_EXPRESSION = eINSTANCE.getEventExpression();

    /**
     * The meta object literal for the '<em><b>Event Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENT_EXPRESSION__EVENT_TYPE = eINSTANCE.getEventExpression_EventType();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT_EXPRESSION__OP = eINSTANCE.getEventExpression_Op();

    /**
     * The meta object literal for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.impl.EventPredicateImpl <em>Event Predicate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.EventPredicateImpl
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getEventPredicate()
     * @generated
     */
    EClass EVENT_PREDICATE = eINSTANCE.getEventPredicate();

    /**
     * The meta object literal for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.impl.TriggerImpl <em>Trigger</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.TriggerImpl
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getTrigger()
     * @generated
     */
    EClass TRIGGER = eINSTANCE.getTrigger();

    /**
     * The meta object literal for the '<em><b>Trigger Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIGGER__TRIGGER_TYPE = eINSTANCE.getTrigger_TriggerType();

    /**
     * The meta object literal for the '<em><b>Returndef</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIGGER__RETURNDEF = eINSTANCE.getTrigger_Returndef();

    /**
     * The meta object literal for the '<em><b>Esig</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIGGER__ESIG = eINSTANCE.getTrigger_Esig();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIGGER__PARAMS = eINSTANCE.getTrigger_Params();

    /**
     * The meta object literal for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.impl.JVMTYPEImpl <em>JVMTYPE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.JVMTYPEImpl
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getJVMTYPE()
     * @generated
     */
    EClass JVMTYPE = eINSTANCE.getJVMTYPE();

    /**
     * The meta object literal for the '<em><b>Astk</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JVMTYPE__ASTK = eINSTANCE.getJVMTYPE_Astk();

    /**
     * The meta object literal for the '<em><b>Jvm Ref</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JVMTYPE__JVM_REF = eINSTANCE.getJVMTYPE_JvmRef();

    /**
     * The meta object literal for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.impl.KindAttributeImpl <em>Kind Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.KindAttributeImpl
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getKindAttribute()
     * @generated
     */
    EClass KIND_ATTRIBUTE = eINSTANCE.getKindAttribute();

    /**
     * The meta object literal for the '<em><b>Locat</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute KIND_ATTRIBUTE__LOCAT = eINSTANCE.getKindAttribute_Locat();

    /**
     * The meta object literal for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.impl.MSigImpl <em>MSig</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.MSigImpl
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getMSig()
     * @generated
     */
    EClass MSIG = eINSTANCE.getMSig();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MSIG__PARAMS = eINSTANCE.getMSig_Params();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MSIG__TYPE = eINSTANCE.getMSig_Type();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MSIG__BODY = eINSTANCE.getMSig_Body();

    /**
     * The meta object literal for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.impl.OrEventImpl <em>Or Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.OrEventImpl
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getOrEvent()
     * @generated
     */
    EClass OR_EVENT = eINSTANCE.getOrEvent();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR_EVENT__LEFT = eINSTANCE.getOrEvent_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR_EVENT__RIGHT = eINSTANCE.getOrEvent_Right();

    /**
     * The meta object literal for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.impl.AndEventImpl <em>And Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.AndEventImpl
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getAndEvent()
     * @generated
     */
    EClass AND_EVENT = eINSTANCE.getAndEvent();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_EVENT__LEFT = eINSTANCE.getAndEvent_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_EVENT__RIGHT = eINSTANCE.getAndEvent_Right();

    /**
     * The meta object literal for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.impl.UnaryEventImpl <em>Unary Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.UnaryEventImpl
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getUnaryEvent()
     * @generated
     */
    EClass UNARY_EVENT = eINSTANCE.getUnaryEvent();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNARY_EVENT__EXPR = eINSTANCE.getUnaryEvent_Expr();

    /**
     * The meta object literal for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.EventType <em>Event Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.escuelaing.reactivexd.reactiveXD.EventType
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getEventType()
     * @generated
     */
    EEnum EVENT_TYPE = eINSTANCE.getEventType();

    /**
     * The meta object literal for the '{@link co.edu.escuelaing.reactivexd.reactiveXD.TPrefix <em>TPrefix</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.escuelaing.reactivexd.reactiveXD.TPrefix
     * @see co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDPackageImpl#getTPrefix()
     * @generated
     */
    EEnum TPREFIX = eINSTANCE.getTPrefix();

  }

} //ReactiveXDPackage
