/**
 * generated by Xtext 2.17.0
 */
package co.edu.escuelaing.reactivexd.reactiveXD;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see co.edu.escuelaing.reactivexd.reactiveXD.ReactiveXDPackage
 * @generated
 */
public interface ReactiveXDFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ReactiveXDFactory eINSTANCE = co.edu.escuelaing.reactivexd.reactiveXD.impl.ReactiveXDFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Decl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Decl</em>'.
   * @generated
   */
  Decl createDecl();

  /**
   * Returns a new object of class '<em>Obsrv Decl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Obsrv Decl</em>'.
   * @generated
   */
  ObsrvDecl createObsrvDecl();

  /**
   * Returns a new object of class '<em>Obsrv Assig</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Obsrv Assig</em>'.
   * @generated
   */
  ObsrvAssig createObsrvAssig();

  /**
   * Returns a new object of class '<em>Event Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Event Expression</em>'.
   * @generated
   */
  EventExpression createEventExpression();

  /**
   * Returns a new object of class '<em>Event Predicate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Event Predicate</em>'.
   * @generated
   */
  EventPredicate createEventPredicate();

  /**
   * Returns a new object of class '<em>Trigger</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Trigger</em>'.
   * @generated
   */
  Trigger createTrigger();

  /**
   * Returns a new object of class '<em>JVMTYPE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>JVMTYPE</em>'.
   * @generated
   */
  JVMTYPE createJVMTYPE();

  /**
   * Returns a new object of class '<em>Kind Attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Kind Attribute</em>'.
   * @generated
   */
  KindAttribute createKindAttribute();

  /**
   * Returns a new object of class '<em>MSig</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MSig</em>'.
   * @generated
   */
  MSig createMSig();

  /**
   * Returns a new object of class '<em>Or Event</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Or Event</em>'.
   * @generated
   */
  OrEvent createOrEvent();

  /**
   * Returns a new object of class '<em>And Event</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>And Event</em>'.
   * @generated
   */
  AndEvent createAndEvent();

  /**
   * Returns a new object of class '<em>Unary Event</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Unary Event</em>'.
   * @generated
   */
  UnaryEvent createUnaryEvent();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  ReactiveXDPackage getReactiveXDPackage();

} //ReactiveXDFactory
