/*
 * generated by Xtext 2.17.0
 */
package co.edu.escuelaing.reactivexd.parser.antlr;

import co.edu.escuelaing.reactivexd.parser.antlr.internal.InternalReactiveXDParser;
import co.edu.escuelaing.reactivexd.services.ReactiveXDGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ReactiveXDParser extends AbstractAntlrParser {

	@Inject
	private ReactiveXDGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalReactiveXDParser createParser(XtextTokenStream stream) {
		return new InternalReactiveXDParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ReactiveXDGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ReactiveXDGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
