/*
 * generated by Xtext 2.17.0
 */
package co.edu.escuelaing.reactivexd.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ReactiveXDAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("co/edu/escuelaing/reactivexd/parser/antlr/internal/InternalReactiveXD.tokens");
	}
}
