/**
 * generated by Xtext 2.17.0
 */
package co.edu.escuelaing.reactivexd.ui.quickfix;

import org.eclipse.xtext.xbase.ui.quickfix.XbaseQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class ReactiveXDQuickfixProvider extends XbaseQuickfixProvider {
}
